# Generated by Django 5.2.17 on 2026-09-05 09:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=128)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("district", "District-level court"),
                            ("provincial", "Provincial-level court"),
                            ("high", "High People's Court"),
                            ("supreme", "Supreme People's Court"),
                        ],
                        max_length=16,
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "superior_court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subordinate_courts",
                        to="cases.court",
                    ),
                ),
            ],
            options={
                "ordering": ("full_name", "code"),
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("individual", "Individual"), ("organization", "Organization")],
                        max_length=16,
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("identity_document_number", models.CharField(blank=True, max_length=64)),
                ("registration_number", models.CharField(blank=True, max_length=64)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("organization_type", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("legal_name", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "kind", "legal_name"], name="case_entity_kind_name_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("identity_document_number__gt", ""),
                                ("kind", "individual"),
                                ("organization_type", ""),
                                ("registration_number", ""),
                            ),
                            models.Q(
                                ("date_of_birth__isnull", True),
                                ("identity_document_number", ""),
                                ("kind", "organization"),
                                ("registration_number__gt", ""),
                            ),
                            _connector="OR",
                        ),
                        name="case_entity_kind_fields_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("identity_document_number", ""), _negated=True),
                        fields=("identity_document_number",),
                        name="case_entity_identity_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("registration_number", ""), _negated=True),
                        fields=("registration_number",),
                        name="case_entity_registration_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent address"),
                            ("current", "Current address"),
                            ("registered_office", "Registered office"),
                            ("contact", "Contact address"),
                        ],
                        max_length=24,
                    ),
                ),
                ("full_address", models.CharField(max_length=500)),
                ("province", models.CharField(blank=True, max_length=128)),
                ("district", models.CharField(blank=True, max_length=128)),
                ("ward", models.CharField(blank=True, max_length=128)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="cases.entity",
                    ),
                ),
            ],
            options={
                "ordering": ("entity", "kind", "-valid_from", "id"),
            },
        ),
        migrations.CreateModel(
            name="Official",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("position", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official",
                        to="cases.entity",
                    ),
                ),
                (
                    "home_court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="officials",
                        to="cases.court",
                    ),
                ),
            ],
            options={
                "ordering": ("entity__legal_name", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="court",
            index=models.Index(
                fields=["is_active", "full_name"], name="case_court_active_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="court",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", models.F("superior_court_id")), _negated=True),
                name="case_court_superior_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="entityaddress",
            index=models.Index(
                fields=["entity", "kind", "valid_to"], name="case_address_history_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityaddress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="case_address_validity_order",
            ),
        ),
        migrations.AddIndex(
            model_name="official",
            index=models.Index(
                fields=["home_court", "is_active"], name="case_official_court_active_idx"
            ),
        ),
    ]
