# Generated by Django 5.2.17 on 2026-09-07 16:24

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("internal_reference", models.CharField(max_length=64, unique=True)),
                ("matter_type", models.CharField(max_length=255)),
                (
                    "procedural_stage",
                    models.CharField(
                        choices=[
                            ("pre_acceptance", "Pre-acceptance"),
                            ("accepted", "Accepted"),
                            ("preparation", "Preparation"),
                            ("hearing", "Hearing"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("acceptance_number", models.CharField(blank=True, max_length=64)),
                (
                    "acceptance_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("acceptance_date", models.DateField(blank=True, null=True)),
                ("acceptance_type_code", models.CharField(blank=True, max_length=32)),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("archive_reason", models.CharField(blank=True, editable=False, max_length=500)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_case_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="cases.court",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_case_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edited_case_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "procedural_stage"], name="case_record_state_stage_idx"
                    ),
                    models.Index(fields=["court", "status"], name="case_record_court_state_idx"),
                    models.Index(
                        fields=["acceptance_year", "acceptance_type_code", "acceptance_date"],
                        name="case_record_acceptance_idx",
                    ),
                    models.Index(fields=["updated_at"], name="case_record_updated_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("acceptance_date__isnull", True),
                                ("acceptance_number", ""),
                                ("acceptance_type_code", ""),
                                ("acceptance_year__isnull", True),
                                ("procedural_stage", "pre_acceptance"),
                            ),
                            models.Q(
                                models.Q(("procedural_stage", "pre_acceptance"), _negated=True),
                                ("acceptance_number__gt", ""),
                                ("acceptance_year__isnull", False),
                                ("acceptance_date__isnull", False),
                                ("acceptance_type_code__gt", ""),
                            ),
                            _connector="OR",
                        ),
                        name="case_record_acceptance_group_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="case_record_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("archive_reason", ""),
                                ("archived_at__isnull", True),
                                ("archived_by__isnull", True),
                                ("status", "active"),
                            ),
                            models.Q(
                                ("archive_reason__gt", ""),
                                ("archived_at__isnull", False),
                                ("archived_by__isnull", False),
                                ("status", "archived"),
                            ),
                            _connector="OR",
                        ),
                        name="case_record_archive_metadata_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "procedural_stage__in",
                                (
                                    "pre_acceptance",
                                    "accepted",
                                    "preparation",
                                    "hearing",
                                    "resolved",
                                ),
                            )
                        ),
                        name="case_record_stage_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("active", "archived"))),
                        name="case_record_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("acceptance_year__isnull", True),
                            models.Q(
                                ("acceptance_year__gte", 1900), ("acceptance_year__lte", 9999)
                            ),
                            _connector="OR",
                        ),
                        name="case_record_acceptance_year_valid",
                    ),
                ],
            },
        ),
    ]
