# Generated by Django 5.2.17 on 2026-09-08 02:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_add_case_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("requester", "Requester"),
                            ("respondent", "Respondent"),
                            ("related_party", "Related party"),
                            ("witness", "Witness"),
                            ("expert", "Expert"),
                            ("interpreter", "Interpreter"),
                            ("rights_protector", "Rights protector"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("case_address", models.TextField(blank=True, max_length=1000)),
                ("case_workplace", models.TextField(blank=True, max_length=500)),
                ("case_contact", models.TextField(blank=True, max_length=500)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="cases.caserecord",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_participations",
                        to="cases.entity",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "id"),
            },
        ),
        migrations.CreateModel(
            name="Representation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "representation_type",
                    models.CharField(
                        choices=[
                            ("legal", "Legal representative"),
                            ("authorized", "Authorized representative"),
                        ],
                        max_length=16,
                    ),
                ),
                ("authority_reference", models.CharField(blank=True, max_length=255)),
                ("authority_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representations",
                        to="cases.caserecord",
                    ),
                ),
                (
                    "representative_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representations_given",
                        to="cases.entity",
                    ),
                ),
                (
                    "represented_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representations",
                        to="cases.caseparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(
                fields=["case", "role", "ordering"], name="case_part_role_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(
                fields=["entity", "is_active", "role"], name="case_part_entity_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(
                fields=["case", "is_active", "effective_from", "effective_to"],
                name="case_part_effective_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        (
                            "requester",
                            "respondent",
                            "related_party",
                            "witness",
                            "expert",
                            "interpreter",
                            "rights_protector",
                            "other",
                        ),
                    )
                ),
                name="case_part_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordering__gte", 0)), name="case_part_order_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="case_part_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("case", "entity", "role"),
                name="case_part_active_role_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="representation",
            index=models.Index(
                fields=["case", "represented_participant"], name="case_repr_case_part_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="representation",
            index=models.Index(
                fields=["representative_entity", "case"], name="case_repr_entity_case_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="representation",
            constraint=models.CheckConstraint(
                condition=models.Q(("representation_type__in", ("legal", "authorized"))),
                name="case_repr_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="representation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=(
                    "case",
                    "representative_entity",
                    "represented_participant",
                    "representation_type",
                ),
                name="case_repr_active_unique",
            ),
        ),
    ]
