# Generated by Django 5.2.17 on 2026-09-08 02:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_add_participants_and_representations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseOfficialAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("judge", "Judge"),
                            ("presiding_judge", "Presiding judge"),
                            ("clerk", "Court clerk"),
                            ("prosecutor", "Prosecutor"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_assignments",
                        to="cases.caserecord",
                    ),
                ),
                (
                    "official",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_assignments",
                        to="cases.official",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "id"),
                "indexes": [
                    models.Index(
                        fields=["case", "role", "ordering"], name="case_assign_role_order_idx"
                    ),
                    models.Index(fields=["official", "role"], name="case_assign_official_idx"),
                    models.Index(
                        fields=["case", "is_active", "effective_from", "effective_to"],
                        name="case_assign_current_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ("judge", "presiding_judge", "clerk", "prosecutor"))
                        ),
                        name="case_assign_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ordering__gte", 0)),
                        name="case_assign_order_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="case_assign_dates_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("case", "official", "role"),
                        name="case_assign_active_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instance_level",
                    models.CharField(
                        choices=[("first_instance", "First-instance"), ("appellate", "Appellate")],
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("location", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("postponed", "Postponed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hearings",
                        to="cases.caserecord",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"], name="case_hearing_upcoming_idx"
                    ),
                    models.Index(
                        fields=["case", "scheduled_at"], name="case_hearing_case_time_idx"
                    ),
                    models.Index(
                        fields=["case", "status", "scheduled_at"],
                        name="case_hearing_case_state_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("instance_level__in", ("first_instance", "appellate"))),
                        name="case_hearing_instance_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ("scheduled", "postponed", "completed", "cancelled"))
                        ),
                        name="case_hearing_status_valid",
                    ),
                ],
            },
        ),
    ]
