# Generated by Django 5.2.17 on 2026-09-11 13:15

import re
import uuid
from typing import Any

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import apps.documents.models

_CREATE_HISTORY_GUARD = r"""
CREATE FUNCTION documents_guard_template_version_history() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'template version history cannot be deleted'
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'uploaded' THEN
            RAISE EXCEPTION 'template versions must start uploaded'
                USING ERRCODE = 'check_violation';
        END IF;
        IF left(NEW.storage_key, char_length(
            'templates/' || NEW.type_key || '/' || NEW.version || '/'
        )) <> ('templates/' || NEW.type_key || '/' || NEW.version || '/') THEN
            RAISE EXCEPTION 'template storage key does not match identity'
                USING ERRCODE = 'check_violation';
        END IF;
        IF btrim(NEW.approval_reference) = '' OR
           jsonb_typeof(NEW.validation_report) <> 'object' OR
           octet_length(NEW.validation_report::text) > 4096 THEN
            RAISE EXCEPTION 'template metadata is invalid'
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF jsonb_typeof(NEW.validation_report) <> 'object' OR
       octet_length(NEW.validation_report::text) > 4096 THEN
        RAISE EXCEPTION 'template validation report is invalid'
            USING ERRCODE = 'check_violation';
    END IF;
    IF ROW(NEW.id, NEW.type_key, NEW.version, NEW.storage_key, NEW.original_filename,
           NEW.checksum_sha256, NEW.byte_size, NEW.uploader_id, NEW.uploaded_at,
           NEW.approval_reference)
       IS DISTINCT FROM
       ROW(OLD.id, OLD.type_key, OLD.version, OLD.storage_key, OLD.original_filename,
           OLD.checksum_sha256, OLD.byte_size, OLD.uploader_id, OLD.uploaded_at,
           OLD.approval_reference) THEN
        RAISE EXCEPTION 'immutable template metadata cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    IF OLD.status <> 'uploaded' AND
       NEW.validation_report IS DISTINCT FROM OLD.validation_report THEN
        RAISE EXCEPTION 'completed validation reports cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.status <> OLD.status AND NOT (
        (OLD.status = 'uploaded' AND NEW.status IN ('valid', 'invalid')) OR
        (OLD.status = 'valid' AND NEW.status = 'active') OR
        (OLD.status = 'active' AND NEW.status = 'inactive') OR
        (OLD.status = 'inactive' AND NEW.status = 'active')
    ) THEN
        RAISE EXCEPTION 'invalid template lifecycle transition'
            USING ERRCODE = 'check_violation';
    END IF;
    IF OLD.activated_at IS NOT NULL AND
       ROW(NEW.activated_at, NEW.activated_by_id) IS DISTINCT FROM
       ROW(OLD.activated_at, OLD.activated_by_id) THEN
        RAISE EXCEPTION 'activation history cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER documents_template_version_history_guard
BEFORE INSERT OR UPDATE OR DELETE ON documents_templateversion
FOR EACH ROW EXECUTE FUNCTION documents_guard_template_version_history();
"""


def _create_history_guard(apps: object, schema_editor: Any) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_CREATE_HISTORY_GUARD)


def _drop_history_guard(apps: object, schema_editor: Any) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS documents_template_version_history_guard "
            "ON documents_templateversion; "
            "DROP FUNCTION IF EXISTS documents_guard_template_version_history();"
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type_key", models.CharField(editable=False, max_length=64)),
                (
                    "version",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
                            )
                        ],
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile(
                                    r"^templates/(?:vds-[0-9]{2}|synthetic-[a-z0-9]+(?:-[a-z0-9]+)*)/[A-Za-z0-9][A-Za-z0-9._-]{0,63}/[0-9a-f]{32}\.docx$"
                                )
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(editable=False, max_length=150)),
                (
                    "checksum_sha256",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator(r"^[0-9a-f]{64}$")],
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10485760),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                (
                    "validation_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[apps.documents.models.validate_validation_report],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("approval_reference", models.CharField(editable=False, max_length=255)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activated_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "ordering": ("type_key", "-uploaded_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["type_key", "status", "-uploaded_at"],
                        name="documents_template_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type_key", "version"),
                        name="documents_template_type_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("type_key",),
                        name="documents_one_active_template_per_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ("uploaded", "valid", "invalid", "active", "inactive"),
                            )
                        ),
                        name="documents_template_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("checksum_sha256__regex", r"^[0-9a-f]{64}$")),
                        name="documents_template_checksum_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type_key__regex",
                                r"^(?:vds-[0-9]{2}|synthetic-[a-z0-9]+(?:-[a-z0-9]+)*)$",
                            )
                        ),
                        name="documents_template_type_key_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("version__regex", r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
                        ),
                        name="documents_template_version_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "storage_key__regex",
                                r"^templates/(?:vds-[0-9]{2}|synthetic-[a-z0-9]+(?:-[a-z0-9]+)*)/[A-Za-z0-9][A-Za-z0-9._-]{0,63}/[0-9a-f]{32}\.docx$",
                            )
                        ),
                        name="documents_template_storage_key_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "storage_key__startswith",
                                django.db.models.functions.text.Concat(
                                    models.Value("templates/"),
                                    models.F("type_key"),
                                    models.Value("/"),
                                    models.F("version"),
                                    models.Value("/"),
                                ),
                            )
                        ),
                        name="documents_template_storage_key_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "original_filename__regex",
                                r"^[^/\\\x00-\x1f\x7f]{1,150}$",
                            )
                        ),
                        name="documents_template_display_filename_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("byte_size__gte", 1), ("byte_size__lte", 10485760)),
                        name="documents_template_size_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("activated_at__isnull", False),
                                ("activated_by__isnull", False),
                                ("status__in", ("active", "inactive")),
                            ),
                            models.Q(
                                ("activated_at__isnull", True),
                                ("activated_by__isnull", True),
                                ("status__in", ("uploaded", "valid", "invalid")),
                            ),
                            _connector="OR",
                        ),
                        name="documents_template_activation_metadata_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(_create_history_guard, _drop_history_guard),
    ]
