# Generated by Django 5.2.17 on 2026-09-12 14:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.documents.models


def _add_postgresql_payload_constraint(apps: object, schema_editor: object) -> None:
    connection = schema_editor.connection  # type: ignore[attr-defined]
    if connection.vendor == "postgresql":
        schema_editor.execute(  # type: ignore[attr-defined]
            "ALTER TABLE documents_documentdraft "
            "ADD CONSTRAINT documents_draft_payload_json_valid "
            "CHECK (jsonb_typeof(payload) = 'object' "
            "AND octet_length(payload::text) <= 65536)"
        )


def _drop_postgresql_payload_constraint(apps: object, schema_editor: object) -> None:
    connection = schema_editor.connection  # type: ignore[attr-defined]
    if connection.vendor == "postgresql":
        schema_editor.execute(  # type: ignore[attr-defined]
            "ALTER TABLE documents_documentdraft "
            "DROP CONSTRAINT IF EXISTS documents_draft_payload_json_valid"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_add_assignments_and_hearings"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type_key", models.CharField(max_length=64)),
                (
                    "schema_version",
                    models.CharField(
                        max_length=16,
                        validators=[django.core.validators.RegexValidator("^v[1-9][0-9]*$")],
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        validators=[apps.documents.models.validate_document_draft_payload]
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_drafts",
                        to="cases.caserecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_document_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edited_document_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["case", "state", "-updated_at"], name="doc_draft_case_state_idx"
                    ),
                    models.Index(
                        fields=["type_key", "schema_version", "state"],
                        name="doc_draft_type_schema_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "type_key", "schema_version"),
                        name="documents_draft_case_type_schema_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ("draft", "ready"))),
                        name="documents_draft_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="documents_draft_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type_key__regex",
                                "^(?:vds-[0-9]{2}|synthetic-[a-z0-9]+(?:-[a-z0-9]+)*)$",
                            )
                        ),
                        name="documents_draft_type_key_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__regex", "^v[1-9][0-9]*$")),
                        name="documents_draft_schema_version_format",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            _add_postgresql_payload_constraint,
            _drop_postgresql_payload_constraint,
        ),
    ]
