# Generated by Django 5.2.17 on 2026-09-13

import uuid
from typing import Any

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Cast, Concat, Replace
from django.db.models.lookups import StartsWith

import apps.documents.models

_CREATE_GENERATION_GUARD = r"""
CREATE FUNCTION documents_guard_generated_document_history() RETURNS trigger AS $$
DECLARE
    referenced_type_key text;
    referenced_version text;
    referenced_checksum text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'generated document history cannot be deleted'
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'generating' THEN
            RAISE EXCEPTION 'generation attempts must start generating'
                USING ERRCODE = 'check_violation';
        END IF;
        SELECT type_key, version, checksum_sha256
          INTO referenced_type_key, referenced_version, referenced_checksum
          FROM documents_templateversion
         WHERE id = NEW.template_version_id;
        IF NOT FOUND
           OR NEW.type_key <> referenced_type_key
           OR NEW.template_snapshot->'identity'->>'id' <> NEW.template_version_id::text
           OR NEW.template_snapshot->'identity'->>'type_key' <> referenced_type_key
           OR NEW.template_snapshot->'identity'->>'version' <> referenced_version
           OR NEW.template_snapshot->'identity'->>'checksum_sha256' <> referenced_checksum THEN
            RAISE EXCEPTION 'generation template facts do not match the protected reference'
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    IF ROW(NEW.id, NEW.case_id, NEW.type_key, NEW.template_version_id,
           NEW.schema_version, NEW.source_draft_id, NEW.case_revision,
           NEW.draft_revision, NEW.input_snapshot, NEW.resolved_values_snapshot,
           NEW.override_snapshot, NEW.template_snapshot, NEW.actor_id,
           NEW.reserved_at, NEW.idempotency_key_hash)
       IS DISTINCT FROM
       ROW(OLD.id, OLD.case_id, OLD.type_key, OLD.template_version_id,
           OLD.schema_version, OLD.source_draft_id, OLD.case_revision,
           OLD.draft_revision, OLD.input_snapshot, OLD.resolved_values_snapshot,
           OLD.override_snapshot, OLD.template_snapshot, OLD.actor_id,
           OLD.reserved_at, OLD.idempotency_key_hash) THEN
        RAISE EXCEPTION 'immutable generation reservation facts cannot change'
            USING ERRCODE = 'check_violation';
    END IF;
    IF OLD.status <> 'generating' OR NEW.status NOT IN ('generated', 'failed') THEN
        RAISE EXCEPTION 'invalid generation lifecycle transition'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER documents_generated_document_history_guard
BEFORE INSERT OR UPDATE OR DELETE ON documents_generateddocument
FOR EACH ROW EXECUTE FUNCTION documents_guard_generated_document_history();
"""


def _create_postgresql_generation_guards(apps: object, schema_editor: Any) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE documents_generateddocument "
        "ADD CONSTRAINT documents_generation_snapshots_valid CHECK ("
        "jsonb_typeof(input_snapshot) = 'object' AND "
        "input_snapshot ?& ARRAY['version', 'values'] AND "
        "input_snapshot - ARRAY['version', 'values'] = '{}'::jsonb AND "
        "jsonb_typeof(input_snapshot->'version') = 'number' AND "
        "input_snapshot->'version' = '1'::jsonb AND "
        "jsonb_typeof(input_snapshot->'values') = 'object' AND "
        "octet_length(input_snapshot::text) <= 65536 AND "
        "jsonb_typeof(resolved_values_snapshot) = 'object' AND "
        "resolved_values_snapshot ?& ARRAY['version', 'values'] AND "
        "resolved_values_snapshot - ARRAY['version', 'values'] = '{}'::jsonb AND "
        "jsonb_typeof(resolved_values_snapshot->'version') = 'number' AND "
        "resolved_values_snapshot->'version' = '1'::jsonb AND "
        "jsonb_typeof(resolved_values_snapshot->'values') = 'object' AND "
        "octet_length(resolved_values_snapshot::text) <= 262144 AND "
        "jsonb_typeof(override_snapshot) = 'object' AND "
        "override_snapshot ?& ARRAY['version', 'values'] AND "
        "override_snapshot - ARRAY['version', 'values'] = '{}'::jsonb AND "
        "jsonb_typeof(override_snapshot->'version') = 'number' AND "
        "override_snapshot->'version' = '1'::jsonb AND "
        "jsonb_typeof(override_snapshot->'values') = 'object' AND "
        "octet_length(override_snapshot::text) <= 65536 AND "
        "jsonb_typeof(template_snapshot) = 'object' AND "
        "template_snapshot ?& ARRAY['version', 'identity'] AND "
        "template_snapshot - ARRAY['version', 'identity'] = '{}'::jsonb AND "
        "jsonb_typeof(template_snapshot->'version') = 'number' AND "
        "template_snapshot->'version' = '1'::jsonb AND "
        "jsonb_typeof(template_snapshot->'identity') = 'object' AND "
        "(template_snapshot->'identity') ?& "
        "ARRAY['id', 'type_key', 'version', 'checksum_sha256'] AND "
        "(template_snapshot->'identity') - "
        "ARRAY['id', 'type_key', 'version', 'checksum_sha256'] = '{}'::jsonb AND "
        "jsonb_typeof(template_snapshot->'identity'->'id') = 'string' AND "
        "jsonb_typeof(template_snapshot->'identity'->'type_key') = 'string' AND "
        "jsonb_typeof(template_snapshot->'identity'->'version') = 'string' AND "
        "jsonb_typeof(template_snapshot->'identity'->'checksum_sha256') = 'string' AND "
        "octet_length(template_snapshot::text) <= 2048)"
    )
    schema_editor.execute(_CREATE_GENERATION_GUARD)


def _drop_postgresql_generation_guards(apps: object, schema_editor: Any) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS documents_generated_document_history_guard "
        "ON documents_generateddocument; "
        "DROP FUNCTION IF EXISTS documents_guard_generated_document_history(); "
        "ALTER TABLE documents_generateddocument "
        "DROP CONSTRAINT IF EXISTS documents_generation_snapshots_valid;"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_add_assignments_and_hearings"),
        ("documents", "0002_add_document_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type_key", models.CharField(editable=False, max_length=64)),
                (
                    "schema_version",
                    models.CharField(
                        editable=False,
                        max_length=16,
                        validators=[django.core.validators.RegexValidator(r"^v[1-9][0-9]*$")],
                    ),
                ),
                ("source_draft_id", models.UUIDField(editable=False)),
                (
                    "case_revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "draft_revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(
                        editable=False,
                        validators=[apps.documents.models.validate_generation_input_snapshot],
                    ),
                ),
                (
                    "resolved_values_snapshot",
                    models.JSONField(
                        editable=False,
                        validators=[apps.documents.models.validate_generation_resolved_snapshot],
                    ),
                ),
                (
                    "override_snapshot",
                    models.JSONField(
                        editable=False,
                        validators=[apps.documents.models.validate_generation_override_snapshot],
                    ),
                ),
                (
                    "template_snapshot",
                    models.JSONField(
                        editable=False,
                        validators=[apps.documents.models.validate_generation_template_snapshot],
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("failed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "idempotency_key_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator(r"^[0-9a-f]{64}$")],
                    ),
                ),
                (
                    "failure_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("template_invalid", "Template invalid"),
                            ("context_missing", "Context missing"),
                            ("render_error", "Render error"),
                            ("storage_error", "Storage error"),
                            ("integrity_error", "Integrity error"),
                        ],
                        default="",
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "failure_correlation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                r"^(?:|[A-Za-z0-9][A-Za-z0-9._:-]{0,127})$"
                            )
                        ],
                    ),
                ),
                (
                    "output_storage_key",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                r"^(?:|generated/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[A-Za-z0-9][A-Za-z0-9._-]{0,144}\.docx)$"
                            )
                        ],
                    ),
                ),
                (
                    "output_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                r"^(?:|[^/\\\x00-\x1f\x7f]{1,145}\.docx)$"
                            )
                        ],
                    ),
                ),
                (
                    "output_size",
                    models.PositiveBigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "output_checksum_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator(r"^(?:|[0-9a-f]{64})$")],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_document_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="cases.caserecord",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_attempts",
                        to="documents.templateversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-reserved_at", "id"),
                "indexes": [
                    models.Index(fields=["case", "-reserved_at"], name="doc_gen_case_history_idx"),
                    models.Index(
                        fields=["type_key", "status", "-reserved_at"],
                        name="doc_generation_type_status_idx",
                    ),
                    models.Index(
                        fields=["actor", "-reserved_at"], name="doc_gen_actor_history_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "idempotency_key_hash"),
                        name="documents_generation_actor_idempotency_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("generating", "generated", "failed"))),
                        name="documents_generation_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type_key__regex",
                                r"^(?:vds-[0-9]{2}|synthetic-[a-z0-9]+(?:-[a-z0-9]+)*)$",
                            )
                        ),
                        name="documents_generation_type_key_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__regex", r"^v[1-9][0-9]*$")),
                        name="documents_generation_schema_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("case_revision__gte", 1), ("draft_revision__gte", 1)),
                        name="documents_generation_revisions_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("idempotency_key_hash__regex", r"^[0-9a-f]{64}$")),
                        name="documents_generation_idempotency_hash_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "failure_correlation_id__regex",
                                r"^(?:|[A-Za-z0-9][A-Za-z0-9._:-]{0,127})$",
                            )
                        ),
                        name="documents_generation_failure_correlation_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "output_storage_key__regex",
                                r"^(?:|generated/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[A-Za-z0-9][A-Za-z0-9._-]{0,144}\.docx)$",
                            )
                        ),
                        name="documents_generation_storage_key_safe",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(output_storage_key="")
                            | models.Q(
                                StartsWith(
                                    Replace(
                                        models.F("output_storage_key"),
                                        models.Value("-"),
                                        models.Value(""),
                                    ),
                                    Concat(
                                        models.Value("generated/"),
                                        Replace(
                                            Cast(models.F("case_id"), models.CharField()),
                                            models.Value("-"),
                                            models.Value(""),
                                        ),
                                        models.Value("/"),
                                        Replace(
                                            Cast(models.F("id"), models.CharField()),
                                            models.Value("-"),
                                            models.Value(""),
                                        ),
                                        models.Value("/"),
                                    ),
                                )
                            )
                        ),
                        name="documents_generation_storage_key_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "output_filename__regex",
                                r"^(?:|[^/\\\x00-\x1f\x7f]{1,145}\.docx)$",
                            )
                        ),
                        name="documents_generation_filename_safe",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                status="generating",
                                generated_at__isnull=True,
                                failed_at__isnull=True,
                                failure_category="",
                                failure_correlation_id="",
                                output_storage_key="",
                                output_filename="",
                                output_size__isnull=True,
                                output_checksum_sha256="",
                            )
                            | (
                                models.Q(
                                    status="generated",
                                    generated_at__isnull=False,
                                    failed_at__isnull=True,
                                    failure_category="",
                                    failure_correlation_id="",
                                    output_size__isnull=False,
                                    output_size__gte=1,
                                    output_checksum_sha256__regex=r"^[0-9a-f]{64}$",
                                )
                                & ~models.Q(output_storage_key="")
                                & ~models.Q(output_filename="")
                            )
                            | (
                                models.Q(
                                    status="failed",
                                    generated_at__isnull=True,
                                    failed_at__isnull=False,
                                    failure_category__in=(
                                        "template_invalid",
                                        "context_missing",
                                        "render_error",
                                        "storage_error",
                                        "integrity_error",
                                    ),
                                    output_storage_key="",
                                    output_filename="",
                                    output_size__isnull=True,
                                    output_checksum_sha256="",
                                )
                                & ~models.Q(failure_correlation_id="")
                            )
                        ),
                        name="documents_generation_status_metadata_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            _create_postgresql_generation_guards,
            _drop_postgresql_generation_guards,
        ),
    ]
