# Generated by Django 5.2.17 on 2026-09-02 11:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_system_actor", models.BooleanField(default=False, editable=False)),
                ("action", models.CharField(db_index=True, editable=False, max_length=64)),
                ("target_type", models.CharField(db_index=True, editable=False, max_length=64)),
                (
                    "target_id",
                    models.CharField(blank=True, default="", editable=False, max_length=128),
                ),
                ("outcome", models.CharField(db_index=True, editable=False, max_length=32)),
                ("correlation_id", models.CharField(db_index=True, editable=False, max_length=128)),
                ("changed_fields", models.JSONField(default=list, editable=False)),
                ("metadata", models.JSONField(default=dict, editable=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"], name="audit_audit_target__59bbff_idx"
                    ),
                    models.Index(
                        fields=["actor", "occurred_at"], name="audit_audit_actor_i_023a4b_idx"
                    ),
                    models.Index(
                        fields=["outcome", "occurred_at"], name="audit_audit_outcome_faf26d_idx"
                    ),
                    models.Index(
                        fields=["correlation_id", "occurred_at"],
                        name="audit_audit_correla_324797_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor__isnull", True), ("is_system_actor", True)),
                            models.Q(("actor__isnull", False), ("is_system_actor", False)),
                            _connector="OR",
                        ),
                        name="audit_event_actor_marker_consistency",
                    )
                ],
            },
        ),
    ]
